Add /lifts endpoint

diff --git a/test_db_scripts/test_prepare b/test_db_scripts/test_prepare
--- a/test_db_scripts/test_prepare
+++ b/test_db_scripts/test_prepare
@@ -9,21 +9,21 @@ psql -lt | cut -d \| -f 1 | grep workout_tracker_test >/dev/null
 TEST_DATABASE_EXISTS=$?
 if [ $TEST_DATABASE_EXISTS -eq 0 ]; then
         echo -e "\nTest database exists. Cleaning...\n"
-        psql -d workout_tracker_test -f clean.sql
+        psql -d postgres -U postgres -c 'DROP DATABASE workout_tracker_test' 
+fi
+
+createdb -U postgres workout_tracker_test
+CREATE_SUCCESSFUL=$?
+if [ $CREATE_SUCCESSFUL -eq 0 ]; then
+        echo -e "Test database created\n"
 else
-        echo -e "\nTest database does not exist. Creating...\n"
-        psql -c "CREATE DATABASE workout_tracker_test"
-        CREATE_SUCCESSFUL=$?
-        if [ $CREATE_SUCCESSFUL -eq 0 ]; then
-                echo -e "Test database created\n"
-        else
-                echo -e "Failed to create test database\n"
-                exit
-        fi
+        echo -e "Failed to create test database\n"
+        exit
 fi
 
 echo -e "\nInitializing test database...\n"
 
-psql -d workout_tracker_test -U postgres -f initialize.sql
+psql -d workout_tracker_test -U postgres -f initialize_workouts.sql
+psql -d workout_tracker_test -U postgres -f initialize_lifts.sql
 
 
